### ISSUE TITLE
The "Settings" menu's options are no longer accessible through keyboard navigation

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/secure-proxy#634]
**[Affected versions]:**
- Firefox Nightly 71.0a1 - Build ID: 20190916093313

**[Affected Platforms]:**
- All Windows
- All Linux
- All Mac

**[Prerequisites]:**
- Have a new Firefox profile with the latest version (v10) of the "Firefox Private Network" add-on installed.
- You are logged in to the "Firefox Private Network".
	
**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Firefox Private Network" toolbar button.
3. Click the "Settings" button from the top-right part of the doorhanger.
4. Press the "Tab" key two times and observe the behavior.

**[Expected result]:**
- The first option from the "Settings" menu is focused.

**[Actual result]:**
- The "Back" button is focused.

**[Notes]:**
- It seems that this issue is a regression, considering the fact that is not reproducible with the 0.9 version of the "Firefox Private Network" add-on.
- If the tab key is pressed one more time after following the steps, the doorhanger will be focused again.
- Attached a screen recording of the issue:
![rec of the issue](https://user-images.githubusercontent.com/31243259/64964797-71621400-d8a4-11e9-844f-dbc5bad0256b.gif)

**Comment by SoftVision-LorandJanos** [comment]
This issue is fixed with the latest version (v0.13) of the "Firefox Private Network" add-on installed on Firefox Release 70.0, Firefox Beta 71.0b3, Firefox Nightly 72.0a1. Tested on Windows 10 x64, Mac 10.14.2 and Ubuntu 16.04 x64, and on the lastest Firefox Nightly 72.0.a1 using Mac 10.15, but  still reproducible on Firefox Release 70.0, Firefox Beta 71.0b3 using Mac 10.15 due to the [Keyboard navigation](https://bugzilla.mozilla.org/show_bug.cgi?id=1587962) bug.
