### ISSUE TITLE
Middle click on any link from Settings opens SP doorhanger in new tab

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/secure-proxy#651]
#### Affected versions:
- Firefox Nightly 71.0.a1
- Firefox Beta 70.0b8.
- Firefox Release 69.0.1.

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04

#### Prerequisites:
The user is logged in to Secure Proxy.

#### Steps to reproduce
1. Display the Secure Proxy doorhanger.
2. Click on the "Settings" button.
3. Open any link from the Settings menu in a new tab, using the middle click.

#### Expected result:
The corresponding link opens in a new tab.

#### Actual result:
A functional Secure Proxy doorhanger is displayed in a new tab for every link.

#### Notes:
This seems to be a regression, considering the fact that this issue was [verified fixed](https://github.com/mozilla/secure-proxy/issues/577#issuecomment-531809160) on the v10 version (from 09/16/2019) of the "Firefox Private Network" add-on using Firefox Nightly (71.0a1 Build ID - 20190916093313). Verified on Windows 10 x64, Mac 10.14.6 and Arch Linux 4.16.6 x64.

![geegee](https://user-images.githubusercontent.com/48829350/65425845-aa0b6b80-de17-11e9-95a0-d41a1285d3de.gif)

**Comment by madalincm** [comment]
During the testing for the v16 unsigned version we have observed some other issues that are reproducing because of this issue:
For example after opening the doorhanger in the new tab the on/off button does not seem to have an effect :
![spOnOffNotWorking](https://user-images.githubusercontent.com/15685441/68943315-83343a80-07b3-11ea-9c3f-36c579913d65.gif)

Marking with the QA Major issue label.

**Comment by SoftVision-LorandJanos** [comment]
This issue is no longer reproducible on the latest version (v16) of the Secure Proxy add-on, using the latest Firefox Nightly (72.0a1). Verified on Windows 10 x64.
