### ISSUE TITLE
Lots of generated FxA tokens in dashboard [v0.9]

### ISSUE THREAD

**Issue by pdehaan** [mozilla/secure-proxy#655]
We've seen this before, but I think only in the context of us locally installing it through WebExt oodles of times. Keith apparently was able to reproduce by simply upgrading from alpha to beta (no uninstalls) on a single profile.

---

Via **Willowhawk** on [Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568240923164700),

**Keith Willowhawk 3:28 PM**
Do the tokens expire after a certain point, and/or are we fixing the beta to only have one active in the device management page?

![image (11)](https://user-images.githubusercontent.com/557895/65456993-6c9ae400-ddff-11e9-953e-aa024fb32d73.png)

**Shane Tomlinson  11 days ago**
Did you uninstall/re-install the addon a whole bunch of times? Or sign in on fresh profiles?

**Keith Willowhawk  10 days ago**
Only upgraded the alpha and then to the beta, no uninstalls.  Only a single profile.

**Liz (:lizzard) Henry 3:29 PM ([Slack](https://mozilla.slack.com/archives/CM2Q7BVHA/p1568240949165200))**
oh that happened to me too at one point. I thought it was fixed though

Yeah. I am also still seeing a lot of these
it makes it look like i have about 40 different devices!

**Comment by bakulf** [comment]
This should be fixed by v12 because we move the authentication flow on the server-side.
@shane-tomlinson do you know why this still happens?

**Comment by shane-tomlinson** [comment]
> @shane-tomlinson do you know why this still happens?

Really, I have no concrete reasons, only theories. I imagine those were created before v12.

I can imagine a new refresh token being created under any of these scenarios:

* Installation on multiple devices
* Uninstall->reinstall addon
* Profile refresh
* Clearing all browser data

Does updating the addon ever request a new refresh token? Does the addon request the user re-authenticate with FxA?

cc @vladikoff since he did a lot of de-dup work. Any ideas how this would come to be? Could we be showing a combination of access & refresh tokens accidentally?

**Comment by bakulf** [comment]
This seems to be already fixed.
