### ISSUE TITLE
getUserMedia Test Page doesn't work with Secure Proxy on

### ISSUE THREAD

**Issue by SoftVision-LorandJanos** [mozilla/secure-proxy#656]
#### Affected versions:
- Firefox Release 69.0.1
- Firefox Beta 70.0b8
- Firefox Nightly 71.0a1

#### Affected Platforms:
- Windows 10 (64-bit)
- MacOS 10.14.5
- Linux Ubuntu 16.04

#### Prerequisites:
Secure Proxy is enabled.

#### Steps to reproduce
1. Go to [GUM](https://mozilla.github.io/webrtc-landing/gum_test.html)
2. Click on the "Audio & Video" button.

#### Expected result:
A prompt for permissions to access the camera and microphone on your machine is displayed.

#### Actual result:
- The prompt is not displayed.
- The WebRTC modal is displayed.

#### Notes:
Works with Secure Proxy turned off.
As stated in https://github.com/mozilla/secure-proxy/issues/376#issue-478927715 GUM should work with SP on.

![Screenshot (199)](https://user-images.githubusercontent.com/48829350/65498454-9964ff00-dec4-11e9-9843-1fb6eae68a71.png)

**Comment by bakulf** [comment]
This is actually the expected behavior. RTCPeerConnection is used by many websites to track the user and we don't show the webRTC modal when that happens. RTCPeerConnection is blocked silently.
We show the dialog when promise-based webRTC methods are called because only with them we know the intent of the website of using webRTC technologies.
