### ISSUE TITLE
Secure Proxy passes are not paused when turning off the proxy

### ISSUE THREAD

**Issue by bsurd** [mozilla/secure-proxy#691]
#### Affected Platforms:
- Linux Ubuntu 19.04 (64-bit)
- Windows 10 (64-bit)
- MacOS 10.14

#### Precondition
- Have SP installed and you are logged in.

#### Steps to reproduce
1. Turn ON SP.
2. Turn OFF SP after 1 or 2 seconds of use.
3. Turn ON SP. 

#### Expected result:
- After re-enabling SP the pass timer should resume from where the user left it.

#### Actual result:
- The timed does not pause when SP is turned off.

#### Notes:
- This is not a very user-friendly experience as he should have 3 hours of usage for each pass. If SP is turned off the timer should remain where SP was turned off.

![1](https://user-images.githubusercontent.com/17178945/66569189-b3b10500-eb73-11e9-86b0-6c68cefe673b.gif)

**Comment by rbillings** [comment]
This is by design, but I understand your point.

**Comment by chrismore** [comment]
As @rbillings mentioned, the timer starts regardless if you start or stop it, which is by design. This may be sufficient or users or not, but that's why it is beta and still an experiment to find the right gates. @bsurd you still have this as a major bug listed in the QA email, but if it is by design and says right on the page:

"At the beginning of each month, you’ll receive four passes to use whenever you want. Passes run without stopping for eight hours."

**Comment by bakulf** [comment]
Removing 'Major issue' because this is how the project has been designed.
We want to experiment different free-tier modes, but we cannot consider this as as a blocker.

**Comment by bsurd** [comment]
Closing the issue.
