### ISSUE TITLE
Add information to proxyEnabled and proxyDisabled telemetry events to help us track pass usage

### ISSUE THREAD

**Issue by arthuredelstein** [mozilla/secure-proxy#781]
We would like to have telemetry for passes -- whether a user is in the pass or unlimited cohort, and when they begin use of a pass.

**Comment by johngruen** [comment]
Adding more detail...

We need a way to track overall usage in both the pass-based and unlimited cohorts...propose we add to `secure.proxy.general.proxyEnabled` and `secure.proxy.general.proxyDisabled` and so that they have an `extra` property of `{pass:${passIndex || -1}` where `passIndex` is the index value (0-11) of the current pass being used and where `-1` is used for users in the unlimited tier.

We also need to track whether users in the tier-based version have the proxy toggled off due to pass expiry...maybe for `secure.proxy.general.proxyDisabled` we add another `value` for `passExpired`
